version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres

    env_file:
      - .env

    environment:
      AIRFLOW_UID: 50000
      _PIP_ADDITIONAL_REQUIREMENTS: -r /opt/airflow/requirements.txt
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins

    ports:
      - ${AIRFLOW_WEBSERVER_PORT}:8080

    command: webserver


  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    restart: always

    depends_on:
      - postgres

    env_file:
      - .env

    environment:
      AIRFLOW_UID: 50000
      _PIP_ADDITIONAL_REQUIREMENTS: -r /opt/airflow/requirements.txt
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - airflow_logs:/opt/airflow/logs
      - airflow_plugins:/opt/airflow/plugins

    command: scheduler

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: -r /opt/airflow/requirements.txt
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: db init
volumes:

  postgres_data:

  airflow_logs:
  airflow_plugins:
